### PR TITLE
Use router path as resource name

### PR DESCRIPTION
**Pull request by inikolaev**

### CODE REVIEW

**Comment by florimondmanca** [comment]
# [Codecov](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28?src=pr&el=h1) Report
> Merging [#28](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28?src=pr&el=desc) into [master](https://codecov.io/gh/florimondmanca/ddtrace-asgi/commit/32ccb56a4713cbe317eb6994b70cbb8924c1812b&el=desc) will **decrease** coverage by `94.07%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##            master     #28       +/-   ##
===========================================
- Coverage   100.00%   5.92%   -94.08%     
===========================================
  Files            9       6        -3     
  Lines          348     253       -95     
===========================================
- Hits           348      15      -333     
- Misses           0     238      +238     
```


| [Impacted Files](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [tests/applications/raw.py](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28/diff?src=pr&el=tree#diff-dGVzdHMvYXBwbGljYXRpb25zL3Jhdy5weQ==) | `0.00% <0.00%> (-100.00%)` | :arrow_down: |
| [tests/applications/fastapi.py](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28/diff?src=pr&el=tree#diff-dGVzdHMvYXBwbGljYXRpb25zL2Zhc3RhcGkucHk=) | `0.00% <0.00%> (-100.00%)` | :arrow_down: |
| [tests/applications/starlette.py](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28/diff?src=pr&el=tree#diff-dGVzdHMvYXBwbGljYXRpb25zL3N0YXJsZXR0ZS5weQ==) | `0.00% <0.00%> (-100.00%)` | :arrow_down: |
| [tests/test\_trace\_middleware.py](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28/diff?src=pr&el=tree#diff-dGVzdHMvdGVzdF90cmFjZV9taWRkbGV3YXJlLnB5) | `6.31% <0.00%> (-93.69%)` | :arrow_down: |
| [tests/utils/asgi.py](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28/diff?src=pr&el=tree#diff-dGVzdHMvdXRpbHMvYXNnaS5weQ==) | | |
| [tests/utils/config.py](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28/diff?src=pr&el=tree#diff-dGVzdHMvdXRpbHMvY29uZmlnLnB5) | | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28?src=pr&el=footer). Last update [32ccb56...d4b61e7](https://codecov.io/gh/florimondmanca/ddtrace-asgi/pull/28?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by inikolaev** [comment]
Can't figure out how to test partial match yet, which causes build to fail due to lower than expected test coverage.

**Comment by florimondmanca** [comment]
> Can't figure out how to test partial match yet

According to this snippet, `Match.PARTIAL` happens when the URL matches but the requested HTTP method isn't allowed by the endpoint:

https://github.com/encode/starlette/blob/508ab752b4f9fb4f5c414eec56f204459297825d/starlette/routing.py#L200-L201

So I assume we should be able to cover that code path by issuing a `POST` to the `path_parameters` endpoint?

**Comment by florimondmanca** [comment]
@inikolaev I pushed and merged two PRs (#29, #30) to clean up the test setup, feel free to merge master back in here — you should have a few issues off your plate. :-)

**Comment by inikolaev** [comment]
> Thanks! This is lookind great so far.
> 
> > Can't figure out how to test partial match yet
> 
> According to this snippet, `Match.PARTIAL` happens when the URL matches but the requested HTTP method isn't allowed by the endpoint:
> 
> https://github.com/encode/starlette/blob/508ab752b4f9fb4f5c414eec56f204459297825d/starlette/routing.py#L200-L201
> 
> So I assume we should be able to cover that code path by issuing a `POST` to the `path_parameters` endpoint?

Yes, I was just confused about which status code to expect, but now it should be fine.

**Comment by inikolaev** [comment]
I made `enrich_span` private for now, this would allow to change name/signature before it's made public.

**Comment by florimondmanca** [comment]
Thanks! I’ll try and leave a review soon. :)

**Comment by inikolaev** [comment]
Did you have a chance to look at it?

**Comment by florimondmanca** [comment]
Hi @inikolaev, I had forgotten about this so no, not yet. I keep the notification in my inbox and plan to address this week. :)

**Comment by florimondmanca** [comment]
Hi @inikolaev, having reviewed this, thought about this a bit more, and found more use cases for customizing the default behavior (eg for my personal website), I don't think this would be the right way to go anymore.

I opened #32 with ideas about an extension mechanism that should also allow you to resolve your use case (although it would indeed require writing _some_ code). Can you take a look over there and confirm? Thanks! I'm closing this in the meantime, thanks for the time you've put into this. :-)

**Comment by inikolaev** [comment]
I’ll take a look! 

Can you take a look at this PR about adding routes to Starlette scope and add some suggestions to make it more framework agnostic, since there’s nothing about routes in the standard: https://github.com/encode/starlette/pull/804/files

**Comment by florimondmanca** [comment]
@inikolaev I don't think it can be made framework agnostic, unfortunately.

The ASGI spec doesn't say anyway about how applications should handle routing (or whether they even have to). I played with the idea of a standardized `routing` ASGI extension, but we'd run across the same problem of "but what if my specific framework wants to add some more information?".

So I think https://github.com/encode/starlette/pull/804 looks good right now. If nothing else if it should allow you to integrate with `ddtrace-asgi` more easily by inspecting the list of matched routes in `scope`. :-) Though that would need to happen _after_ route matching happened, so _after_ the app was called into… Might need to add one more hook to #32 as it currently doesn't support modifying the span after the response was sent.

**Comment by inikolaev** [comment]
That true, if frameworks want to add some framework-specific fields, that should be put into some standardized namespace, to avoid clashing with standard fields added in the future.

**Pull request closed without merging**
